"""PDF generation: Payment Vouchers, Payment Listings, Payslips.

All PDF text is English-only — reportlab's built-in Helvetica cannot render
Chinese characters or emoji (they appear as black boxes).
File names follow: PV-0001_TNJ-Design.pdf / PL-0001_2026-07-05.pdf /
PAYSLIP_Jul-2026_Karen.pdf
"""
import os
import re
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

UPLOAD_DIR = os.environ.get("UPLOAD_DIR", "uploads")
ORANGE = colors.HexColor("#7F2F01")
ORANGE_MID = colors.HexColor("#A6450F")
LIGHT = colors.HexColor("#FCE4D6")
GRAY = colors.HexColor("#666666")

styles = getSampleStyleSheet()
H1 = ParagraphStyle("h1", parent=styles["Title"], textColor=ORANGE, fontSize=17, spaceAfter=1)
H2 = ParagraphStyle("h2", parent=styles["Heading2"], alignment=1, spaceBefore=4, textColor=ORANGE_MID)
SMALL = ParagraphStyle("small", parent=styles["Normal"], fontSize=9)
TINY = ParagraphStyle("tiny", parent=styles["Normal"], fontSize=7.5, textColor=GRAY)


def safe_name(s: str, maxlen: int = 40) -> str:
    """Filesystem-safe slug: 'TNJ Design Sdn Bhd' -> 'TNJ-Design-Sdn-Bhd'."""
    s = re.sub(r"[^\w\s-]", "", s or "").strip()
    s = re.sub(r"[\s_]+", "-", s)
    return (s or "unnamed")[:maxlen]


def _header(el, company, address, doc_title):
    el.append(Paragraph(company, H1))
    if address:
        el.append(Paragraph(address, SMALL))
    el.append(Spacer(1, 2 * mm))
    el.append(HRFlowable(width="100%", thickness=1.2, color=ORANGE))
    el.append(Paragraph(doc_title, H2))
    el.append(Spacer(1, 4 * mm))


def _sig_block(labels):
    cells = [["_" * 28 for _ in labels], labels]
    t = Table(cells, colWidths=[170 * mm / len(labels)] * len(labels), hAlign="CENTER")
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, 0), 36),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    return t


def _grid_style(last_bold=True):
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), ORANGE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#FDF3EC")]),
    ]
    if last_bold:
        style += [
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("BACKGROUND", (0, -1), (-1, -1), LIGHT),
        ]
    return TableStyle(style)


def voucher_pdf(pv_no: str, payee: str, items: list[dict], total: float,
                company="CATDAY SDN BHD", address="Uptown PJ") -> str:
    """items: [{date, description, amount}]. Returns relative pdf path."""
    subdir = f"vouchers/{date.today():%Y-%m}"
    os.makedirs(os.path.join(UPLOAD_DIR, subdir), exist_ok=True)
    rel = f"{subdir}/{pv_no}_{safe_name(payee)}.pdf"
    doc = SimpleDocTemplate(os.path.join(UPLOAD_DIR, rel), pagesize=A4,
                            topMargin=16 * mm, bottomMargin=16 * mm)
    el = []
    _header(el, company, address, "PAYMENT VOUCHER")

    info = Table([
        ["Voucher No.:", pv_no, "Date:", f"{date.today():%d/%m/%Y}"],
        ["Payee:", payee, "", ""],
    ], colWidths=[30 * mm, 75 * mm, 20 * mm, 40 * mm])
    info.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
        ("TEXTCOLOR", (2, 0), (2, -1), GRAY),
    ]))
    el.append(info)
    el.append(Spacer(1, 6 * mm))

    data = [["No.", "Date", "Description", "Amount (RM)"]]
    for i, it in enumerate(items, 1):
        data.append([str(i), it["date"], Paragraph(it["description"], SMALL), f"{it['amount']:,.2f}"])
    data.append(["", "", "TOTAL", f"{total:,.2f}"])
    t = Table(data, colWidths=[12 * mm, 24 * mm, 102 * mm, 32 * mm], repeatRows=1)
    t.setStyle(_grid_style())
    t.setStyle(TableStyle([("ALIGN", (3, 0), (3, -1), "RIGHT")]))
    el.append(t)
    el.append(Spacer(1, 8 * mm))
    el.append(_sig_block(["Prepared By", "Approved By", "Received By"]))
    el.append(Spacer(1, 4 * mm))
    el.append(Paragraph(f"Generated by CATDAY System - {pv_no}", TINY))
    doc.build(el)
    return rel


def listing_pdf(pl_no: str, vouchers: list[dict], total: float,
                company="CATDAY SDN BHD", address="Uptown PJ") -> str:
    """vouchers: [{pv_no, date, payee, total}]."""
    subdir = f"listings/{date.today():%Y-%m}"
    os.makedirs(os.path.join(UPLOAD_DIR, subdir), exist_ok=True)
    rel = f"{subdir}/{pl_no}_{date.today():%Y-%m-%d}.pdf"
    doc = SimpleDocTemplate(os.path.join(UPLOAD_DIR, rel), pagesize=A4,
                            topMargin=16 * mm, bottomMargin=16 * mm)
    el = []
    _header(el, company, address, "PAYMENT LISTING")
    el.append(Paragraph(f"Listing No: {pl_no}     Date: {date.today():%d/%m/%Y}     "
                        f"Vouchers: {len(vouchers)}", styles["Normal"]))
    el.append(Spacer(1, 5 * mm))

    data = [["No.", "PV No.", "Date", "Payee", "Amount (RM)"]]
    for i, v in enumerate(vouchers, 1):
        data.append([str(i), v["pv_no"], v["date"], Paragraph(v["payee"], SMALL), f"{v['total']:,.2f}"])
    data.append(["", "", "", "GRAND TOTAL", f"{total:,.2f}"])
    t = Table(data, colWidths=[12 * mm, 24 * mm, 24 * mm, 78 * mm, 32 * mm], repeatRows=1)
    t.setStyle(_grid_style())
    t.setStyle(TableStyle([("ALIGN", (4, 0), (4, -1), "RIGHT")]))
    el.append(t)
    el.append(Spacer(1, 8 * mm))
    el.append(_sig_block(["Prepared By", "Approved By"]))
    el.append(Spacer(1, 4 * mm))
    el.append(Paragraph(f"Generated by CATDAY System - {pl_no}", TINY))
    doc.build(el)
    return rel


def payslip_pdf(month: str, item, company="CATDAY SDN BHD", address="Uptown PJ") -> str:
    """item: PayrollItem. Returns relative pdf path."""
    subdir = f"payslips/{safe_name(month)}"
    os.makedirs(os.path.join(UPLOAD_DIR, subdir), exist_ok=True)
    rel = f"{subdir}/PAYSLIP_{safe_name(month)}_{safe_name(item.staff_name)}.pdf"
    doc = SimpleDocTemplate(os.path.join(UPLOAD_DIR, rel), pagesize=A4,
                            topMargin=16 * mm, bottomMargin=16 * mm)
    el = []
    _header(el, company, address, f"PAYSLIP — {month}")

    info = Table([
        ["Employee:", item.staff_name, "Position:", item.position],
        ["Pay Period:", month, "Payslip Date:", f"{date.today():%d/%m/%Y}"],
    ], colWidths=[28 * mm, 62 * mm, 30 * mm, 50 * mm])
    info.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), GRAY),
        ("TEXTCOLOR", (2, 0), (2, -1), GRAY),
    ]))
    el.append(info)
    el.append(Spacer(1, 6 * mm))

    earnings = [
        ["EARNINGS", "RM"],
        ["Basic Salary", f"{item.base:,.2f}"],
    ]
    if item.allowance:
        earnings.append(["Allowance", f"{item.allowance:,.2f}"])
    if item.overtime:
        earnings.append(["Overtime", f"{item.overtime:,.2f}"])
    if item.bonus:
        earnings.append(["Bonus", f"{item.bonus:,.2f}"])
    earnings.append(["Gross Pay", f"{item.gross:,.2f}"])

    deductions = [
        ["DEDUCTIONS", "RM"],
        ["EPF (Employee)", f"{item.epf_ee:,.2f}"],
        ["SOCSO (Employee)", f"{item.socso_ee:,.2f}"],
        ["EIS (Employee)", f"{item.eis_ee:,.2f}"],
    ]
    if item.deductions:
        deductions.append(["Other Deductions", f"{item.deductions:,.2f}"])
    total_ded = item.epf_ee + item.socso_ee + item.eis_ee + item.deductions
    deductions.append(["Total Deductions", f"{total_ded:,.2f}"])

    te = Table(earnings, colWidths=[55 * mm, 28 * mm])
    td = Table(deductions, colWidths=[55 * mm, 28 * mm])
    for t in (te, td):
        t.setStyle(_grid_style())
        t.setStyle(TableStyle([("ALIGN", (1, 0), (1, -1), "RIGHT")]))
    pair = Table([[te, td]], colWidths=[88 * mm, 88 * mm])
    pair.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
    el.append(pair)
    el.append(Spacer(1, 6 * mm))

    net = Table([["NET PAY", f"RM {item.net:,.2f}"]], colWidths=[120 * mm, 51 * mm])
    net.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), ORANGE),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 12),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    el.append(net)
    el.append(Spacer(1, 5 * mm))

    er = Table([
        ["EMPLOYER CONTRIBUTIONS (not deducted from pay)", "RM"],
        ["EPF (Employer)", f"{item.epf_er:,.2f}"],
        ["SOCSO (Employer)", f"{item.socso_er:,.2f}"],
        ["EIS (Employer)", f"{item.eis_er:,.2f}"],
        ["Total Employer Cost", f"{item.employer_cost:,.2f}"],
    ], colWidths=[120 * mm, 51 * mm])
    er.setStyle(_grid_style())
    er.setStyle(TableStyle([("ALIGN", (1, 0), (1, -1), "RIGHT")]))
    el.append(er)

    if item.remarks:
        el.append(Spacer(1, 4 * mm))
        el.append(Paragraph(f"Remarks: {item.remarks}", SMALL))

    el.append(Spacer(1, 8 * mm))
    el.append(_sig_block(["Employer", "Employee"]))
    el.append(Spacer(1, 4 * mm))
    el.append(Paragraph("This is a computer-generated payslip. Generated by CATDAY System.", TINY))
    doc.build(el)
    return rel
